<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="t11" tests="1" failures="1" timestamp="16 Dec 2017 15:49:12 GMT" time="93.009" errors="0">
  <testcase name="DO" time="90.46" classname="com.tata.selenium.test.supplierProvisioningCases.TC_10_NewSupplierEditing">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.supplierProvisioningCases.TC_10_NewSupplierEditing.DO(TC_10_NewSupplierEditing.java:280)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- t11 -->
