<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="t2" tests="1" failures="1" timestamp="15 Aug 2017 06:09:22 GMT" time="112.693" errors="0">
  <testcase name="DO" time="109.997" classname="com.tata.selenium.test.supplierProvisioningCases.TC_020_SupplierCreation">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:261)
	at com.tata.selenium.test.supplierProvisioningCases.TC_020_SupplierCreation.DO(TC_020_SupplierCreation.java:161)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- t2 -->
