<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="t3" tests="1" failures="1" timestamp="17 Dec 2017 03:12:28 GMT" time="25.864" errors="0">
  <testcase name="DO" time="24.274" classname="com.tata.selenium.test.inventoryNumberManagement.TC_02_SC_LN_NumberLengthValidation">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.inventoryNumberManagement.TC_02_SC_LN_NumberLengthValidation.DO(TC_02_SC_LN_NumberLengthValidation.java:145)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- t3 -->
