<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="t4" tests="1" failures="1" timestamp="17 Dec 2017 10:15:52 GMT" time="98.479" errors="0">
  <testcase name="DO" time="94.665" classname="com.tata.selenium.test.productCoverageCases.TC_02_ProductCoverageMTSMS">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.productCoverageCases.TC_02_ProductCoverageMTSMS.DO(TC_02_ProductCoverageMTSMS.java:177)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- t4 -->
