<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="t5" tests="1" failures="1" timestamp="17 Dec 2017 15:11:34 GMT" time="69.82" errors="0">
  <testcase name="DO" time="66.863" classname="com.tata.selenium.test.productPriceManagement.TC_04_ValidateNegativePrice">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.productPriceManagement.TC_04_ValidateNegativePrice.DO(TC_04_ValidateNegativePrice.java:162)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- t5 -->
