<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="t5" tests="1" failures="1" timestamp="16 Dec 2017 17:00:38 GMT" time="190.591" errors="0">
  <testcase name="DO" time="187.741" classname="com.tata.selenium.test.supplierCoverageCases.TC_002_SupplierCoverageMTSMS">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.supplierCoverageCases.TC_002_SupplierCoverageMTSMS.DO(TC_002_SupplierCoverageMTSMS.java:212)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- t5 -->
