<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="TC_06" tests="1" failures="1" timestamp="18 Dec 2017 05:39:26 GMT" time="89.738" errors="0">
  <testcase name="DO" time="87.942" classname="com.tata.selenium.test.customerPriceMgmtCases.TC_06_UploadCSVWithValidDate">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:272)
	at com.tata.selenium.test.customerPriceMgmtCases.TC_06_UploadCSVWithValidDate.DO(TC_06_UploadCSVWithValidDate.java:114)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- TC_06 -->
