<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="TC_06" tests="1" failures="1" timestamp="16 Dec 2017 18:56:56 GMT" time="59.651" errors="0">
  <testcase name="DO" time="55.359" classname="com.tata.selenium.test.supplierCostManagementCases.TC_05_SupplierCostMgmtAddCostAndCalendar">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:271)
	at com.tata.selenium.test.supplierCostManagementCases.TC_05_SupplierCostMgmtAddCostAndCalendar.DO(TC_05_SupplierCostMgmtAddCostAndCalendar.java:184)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- TC_06 -->
