<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pavilion" name="TC_02" tests="1" failures="1" timestamp="18 Dec 2017 04:25:01 GMT" time="106.298" errors="0">
  <testcase name="DO" time="102.57" classname="com.tata.selenium.test.customerPriceMgmtCases.TC_02_AddCoverage">
    <failure type="java.lang.AssertionError" message="Test case is having some failed/warning steps. Please check in the report">
      <![CDATA[java.lang.AssertionError: Test case is having some failed/warning steps. Please check in the report
	at com.tata.selenium.utils.CommonUtils.checkRunStatus(CommonUtils.java:272)
	at com.tata.selenium.test.customerPriceMgmtCases.TC_02_AddCoverage.DO(TC_02_AddCoverage.java:146)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- DO -->
</testsuite> <!-- TC_02 -->
